# Generated by Django 4.2.2 on 2023-07-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.division')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='division',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.zone'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='division',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.division'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='subdivision',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.subdivision'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.zone'),
        ),
    ]
