# Generated by Django 4.2.2 on 2023-07-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_consumer_division_subdivision_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='subdivision',
            field=models.ForeignKey(blank=True, default='Adabari', on_delete=django.db.models.deletion.CASCADE, to='person.subdivision'),
        ),
    ]
