# Generated by Django 4.2.2 on 2023-07-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_consumer_subdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='subdivision',
        ),
    ]
